# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: adrhinum.keymapper
PackageVersion: "0.4.1"
Platform:
  - Windows.Desktop
Installers:
  - Architecture: x64
    InstallerType: inno
    Scope: user
    InstallerUrl: "https://github.com/mamrhein/keymapper.rs/releases/download/v0.4.1/keymapper-v0.4.1-x86_64-pc-windows-msvc-setup.exe"
    # Replaced by the winget-pkgs workflow with the release asset checksum.
    InstallerSha256: "0628df2e0c8feb9e899ba1151d4de77f5b839d7528415e3b555c157f4627c6ff"
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
ManifestType: installer
ManifestVersion: 1.10.0
